#!/usr/bin/env bash
# Generated by catppuccin-tiling-mode.sh
export CATPPUCCIN_FLAVOUR="mocha"
export BAR_COLOR=0xee1e1e2e
export ITEM_BG=0xcc181825
export ITEM_BG_ALT=0xaa313244
export TEXT=0xffcdd6f4
export SUBTEXT=0xffa6adc8
export MUTED=0xff6c7086
export ACCENT=0xffcba6f7
export ACCENT_ALT=0xff89b4fa
export SUCCESS=0xffa6e3a1
export WARN=0xfff9e2af
export ERROR=0xfff38ba8
export BORDER=0xff45475a
export CRUST=0xff11111b
export TRANSPARENT=0x00000000
