#!/usr/bin/env bash
# Generated by catppuccin-tiling-mode.sh
export CATPPUCCIN_FLAVOUR="latte"
export BAR_COLOR=0xeeeff1f5
export ITEM_BG=0xcce6e9ef
export ITEM_BG_ALT=0xaaccd0da
export TEXT=0xff4c4f69
export SUBTEXT=0xff6c6f85
export MUTED=0xff9ca0b0
export ACCENT=0xff8839ef
export ACCENT_ALT=0xff1e66f5
export SUCCESS=0xff40a02b
export WARN=0xffdf8e1d
export ERROR=0xffd20f39
export BORDER=0xffbcc0cc
export CRUST=0xffdce0e8
export TRANSPARENT=0x00000000
