require("items.widgets.appearance")
require("items.widgets.volume")
require("items.widgets.cpu")
require("items.widgets.gpu")
require("items.widgets.memory")
require("items.widgets.wifi")
require("items.widgets.weather")
require("items.widgets.sketchyvim")
