#!/usr/bin/env bash
set -Eeuo pipefail

ACTION="${1:-apply}"
FLAVOUR="${2:-mocha}"

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CONFIG_HOME/ricing"
SKETCHYBAR_DIR="$CONFIG_HOME/sketchybar"
WALLPAPER_DIR="$CONFIG_HOME/wallpapers/catppuccin"
KITTY_CONFIG="$CONFIG_HOME/kitty/kitty.conf"
KITTY_OPACITY_SCRIPT="$CONFIG_HOME/scripts/kitty-opacity.sh"
DEFAULT_OPACITY="${CATPPUCCIN_TILING_OPACITY:-70}"

mkdir -p "$STATE_DIR" "$SKETCHYBAR_DIR"

normalise_flavour() {
  case "${1,,}" in
    latte|frappe|macchiato|mocha) printf '%s\n' "${1,,}" ;;
    catppuccin-latte) printf 'latte\n' ;;
    catppuccin-frappe) printf 'frappe\n' ;;
    catppuccin-macchiato) printf 'macchiato\n' ;;
    catppuccin-mocha) printf 'mocha\n' ;;
    *) printf 'mocha\n' ;;
  esac
}

title_flavour() {
  local value
  value="$(normalise_flavour "$1")"
  printf '%s%s\n' "$(printf '%s' "${value:0:1}" | tr '[:lower:]' '[:upper:]')" "${value:1}"
}

palette() {
  case "$(normalise_flavour "$1")" in
    latte)
      BASE=eff1f5; MANTLE=e6e9ef; CRUST=dce0e8; TEXT=4c4f69; SUBTEXT=6c6f85
      SURFACE0=ccd0da; SURFACE1=bcc0cc; OVERLAY0=9ca0b0; BLUE=1e66f5
      LAVENDER=7287fd; MAUVE=8839ef; GREEN=40a02b; YELLOW=df8e1d; RED=d20f39
      ;;
    frappe)
      BASE=303446; MANTLE=292c3c; CRUST=232634; TEXT=c6d0f5; SUBTEXT=a5adce
      SURFACE0=414559; SURFACE1=51576d; OVERLAY0=737994; BLUE=8caaee
      LAVENDER=babbf1; MAUVE=ca9ee6; GREEN=a6d189; YELLOW=e5c890; RED=e78284
      ;;
    macchiato)
      BASE=24273a; MANTLE=1e2030; CRUST=181926; TEXT=cad3f5; SUBTEXT=a5adcb
      SURFACE0=363a4f; SURFACE1=494d64; OVERLAY0=6e738d; BLUE=8aadf4
      LAVENDER=b7bdf8; MAUVE=c6a0f6; GREEN=a6da95; YELLOW=eed49f; RED=ed8796
      ;;
    *)
      BASE=1e1e2e; MANTLE=181825; CRUST=11111b; TEXT=cdd6f4; SUBTEXT=a6adc8
      SURFACE0=313244; SURFACE1=45475a; OVERLAY0=6c7086; BLUE=89b4fa
      LAVENDER=b4befe; MAUVE=cba6f7; GREEN=a6e3a1; YELLOW=f9e2af; RED=f38ba8
      ;;
  esac
}

write_sketchybar_colors() {
  local flavour="$1"
  palette "$flavour"

  cat > "$SKETCHYBAR_DIR/colors.sh" <<EOF
#!/usr/bin/env bash
# Generated by catppuccin-tiling-mode.sh
export CATPPUCCIN_FLAVOUR="$(normalise_flavour "$flavour")"
export BAR_COLOR=0xee$BASE
export ITEM_BG=0xcc$MANTLE
export ITEM_BG_ALT=0xaa$SURFACE0
export TEXT=0xff$TEXT
export SUBTEXT=0xff$SUBTEXT
export MUTED=0xff$OVERLAY0
export ACCENT=0xff$MAUVE
export ACCENT_ALT=0xff$BLUE
export SUCCESS=0xff$GREEN
export WARN=0xff$YELLOW
export ERROR=0xff$RED
export BORDER=0xff$SURFACE1
export CRUST=0xff$CRUST
export TRANSPARENT=0x00000000
EOF
}

reload_sketchybar() {
  command -v sketchybar >/dev/null 2>&1 || return 0
  pgrep -x sketchybar >/dev/null 2>&1 || return 0
  sketchybar --reload >/dev/null 2>&1 || true
}

current_wallpaper() {
  osascript -e 'tell application "System Events" to tell desktop 1 to get picture' 2>/dev/null || true
}

wallpaper_for_flavour() {
  local flavour title exact
  flavour="$(normalise_flavour "$1")"
  title="$(title_flavour "$flavour")"
  exact="$WALLPAPER_DIR/Catppuccin Apple ($title).png"

  if [[ -f "$exact" ]]; then
    printf '%s\n' "$exact"
    return 0
  fi

  find "$WALLPAPER_DIR" -maxdepth 1 -type f \
    \( -iname "*$title*.png" -o -iname "*$flavour*.png" -o -iname "*$title*.jpg" -o -iname "*$flavour*.jpg" \) \
    2>/dev/null | head -n 1
}

set_wallpaper() {
  local wallpaper="$1"
  [[ -f "$wallpaper" ]] || return 1
  osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"$wallpaper\"" >/dev/null 2>&1 || return 1
}

desktop_icon_state() {
  defaults read com.apple.finder CreateDesktop 2>/dev/null || printf '__unset__\n'
}

set_desktop_icons() {
  local enabled="$1"
  defaults write com.apple.finder CreateDesktop -bool "$enabled" >/dev/null
  killall Finder >/dev/null 2>&1 || true
}

active_kitty_opacity() {
  awk '
    /^[[:space:]]*background_opacity[[:space:]]+/ { print $2; found = 1; exit }
    END { if (!found) print "__unset__" }
  ' "$KITTY_CONFIG" 2>/dev/null || printf '__unset__\n'
}

remove_kitty_opacity() {
  local tmp
  [[ -f "$KITTY_CONFIG" ]] || return 0
  tmp="$(mktemp "${TMPDIR:-/tmp}/kitty.conf.XXXXXX")"
  awk '!/^[[:space:]]*background_opacity[[:space:]]+/' "$KITTY_CONFIG" > "$tmp"
  mv "$tmp" "$KITTY_CONFIG"
  command -v kitty >/dev/null 2>&1 || return 0
  kitty @ set-background-opacity --all 1 >/dev/null 2>&1 || kitty @ load-config "$KITTY_CONFIG" >/dev/null 2>&1 || true
}

save_state_once() {
  [[ -f "$STATE_DIR/active" ]] && [[ "$(cat "$STATE_DIR/active" 2>/dev/null)" == "1" ]] && return 0
  current_wallpaper > "$STATE_DIR/previous_wallpaper"
  desktop_icon_state > "$STATE_DIR/previous_desktop_icons"
  active_kitty_opacity > "$STATE_DIR/previous_kitty_opacity"
}

mark_state() {
  local active="$1"
  local flavour="$2"
  printf '%s\n' "$active" > "$STATE_DIR/active"
  printf '%s\n' "$(normalise_flavour "$flavour")" > "$STATE_DIR/theme"
}

apply_mode() {
  local flavour wallpaper
  flavour="$(normalise_flavour "$1")"

  save_state_once
  write_sketchybar_colors "$flavour"

  wallpaper="$(wallpaper_for_flavour "$flavour")"
  if [[ -n "$wallpaper" ]]; then
    set_wallpaper "$wallpaper" || printf 'warning: could not set wallpaper: %s\n' "$wallpaper" >&2
  else
    printf 'warning: no %s wallpaper found in %s\n' "$flavour" "$WALLPAPER_DIR" >&2
  fi

  set_desktop_icons false
  "$KITTY_OPACITY_SCRIPT" "$DEFAULT_OPACITY" >/dev/null
  mark_state 1 "$flavour"
  reload_sketchybar
}

restore_mode() {
  local previous_wallpaper previous_icons previous_opacity

  write_sketchybar_colors "$(normalise_flavour "$FLAVOUR")"

  previous_wallpaper="$(cat "$STATE_DIR/previous_wallpaper" 2>/dev/null || true)"
  if [[ -n "$previous_wallpaper" && -f "$previous_wallpaper" ]]; then
    set_wallpaper "$previous_wallpaper" || true
  fi

  previous_icons="$(cat "$STATE_DIR/previous_desktop_icons" 2>/dev/null || printf '1\n')"
  if [[ "$previous_icons" == "__unset__" || "$previous_icons" == "1" || "$previous_icons" == "true" ]]; then
    set_desktop_icons true
  else
    set_desktop_icons false
  fi

  previous_opacity="$(cat "$STATE_DIR/previous_kitty_opacity" 2>/dev/null || printf '__unset__\n')"
  if [[ "$previous_opacity" == "__unset__" || -z "$previous_opacity" ]]; then
    remove_kitty_opacity
  else
    "$KITTY_OPACITY_SCRIPT" "$previous_opacity" >/dev/null
  fi

  mark_state 0 "$FLAVOUR"
  reload_sketchybar
}

case "$ACTION" in
  apply|enter|on)
    apply_mode "$FLAVOUR"
    ;;
  restore|exit|off)
    restore_mode
    ;;
  colors)
    write_sketchybar_colors "$FLAVOUR"
    reload_sketchybar
    ;;
  *)
    printf 'Usage: %s apply|restore|colors [latte|frappe|macchiato|mocha]\n' "${0##*/}" >&2
    exit 2
    ;;
esac
