#!/usr/bin/env bash
set -Eeuo pipefail

ACTION="${1:-apply}"
FLAVOUR="${2:-mocha}"

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CONFIG_HOME/ricing"
SKETCHYBAR_DIR="$CONFIG_HOME/sketchybar"
SKETCHYBAR_ACTIVE_THEME="$SKETCHYBAR_DIR/helpers/active_theme.txt"
WALLPAPER_DIR="$CONFIG_HOME/wallpapers/catppuccin"
KITTY_CONFIG="$CONFIG_HOME/kitty/kitty.conf"
KITTY_CURRENT_THEME="$CONFIG_HOME/kitty/current-theme.conf"
STARSHIP_CONFIG="$CONFIG_HOME/starship.toml"
KITTY_OPACITY_SCRIPT="$CONFIG_HOME/scripts/kitty-opacity.sh"
JANKYBORDERS_SCRIPT="$CONFIG_HOME/scripts/jankyborders.sh"
SKETCHYVIM_SCRIPT="$CONFIG_HOME/scripts/sketchyvim-toggle.sh"
SOUND_SCRIPT="$CONFIG_HOME/scripts/aesthetic-sound.sh"
NVIM_STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/nvim"
DEFAULT_OPACITY="${CATPPUCCIN_TILING_OPACITY:-70}"

mkdir -p "$STATE_DIR" "$SKETCHYBAR_DIR" "$SKETCHYBAR_DIR/helpers"

mark_manual_theme_choice() {
  [[ "${CATPPUCCIN_AUTO_SYNC:-0}" == "1" ]] && return 0
  [[ "${CATPPUCCIN_KEEP_AUTO:-0}" == "1" ]] && return 0
  printf '0\n' > "$STATE_DIR/auto_appearance_enabled"
}

normalise_flavour() {
  local value
  value="$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')"

  case "$value" in
    latte|frappe|macchiato|mocha) printf '%s\n' "$value" ;;
    catppuccin-latte) printf 'latte\n' ;;
    catppuccin-frappe) printf 'frappe\n' ;;
    catppuccin-macchiato) printf 'macchiato\n' ;;
    catppuccin-mocha) printf 'mocha\n' ;;
    *) printf 'mocha\n' ;;
  esac
}

title_flavour() {
  local value
  value="$(normalise_flavour "$1")"
  printf '%s%s\n' "$(printf '%s' "${value:0:1}" | tr '[:lower:]' '[:upper:]')" "${value:1}"
}

kitty_theme_name() {
  case "$(normalise_flavour "$1")" in
    latte) printf 'Catppuccin-Latte\n' ;;
    frappe) printf 'Catppuccin-Frappe\n' ;;
    macchiato) printf 'Catppuccin-Macchiato\n' ;;
    *) printf 'Catppuccin-Mocha\n' ;;
  esac
}

palette() {
  case "$(normalise_flavour "$1")" in
    latte)
      BASE=eff1f5; MANTLE=e6e9ef; CRUST=dce0e8; TEXT=4c4f69; SUBTEXT=6c6f85
      SURFACE0=ccd0da; SURFACE1=bcc0cc; OVERLAY0=9ca0b0; BLUE=1e66f5
      ROSEWATER=dc8a78; TEAL=179299
      LAVENDER=7287fd; MAUVE=8839ef; GREEN=40a02b; YELLOW=df8e1d; RED=d20f39
      ;;
    frappe)
      BASE=303446; MANTLE=292c3c; CRUST=232634; TEXT=c6d0f5; SUBTEXT=a5adce
      SURFACE0=414559; SURFACE1=51576d; OVERLAY0=737994; BLUE=8caaee
      ROSEWATER=f2d5cf; TEAL=81c8be
      LAVENDER=babbf1; MAUVE=ca9ee6; GREEN=a6d189; YELLOW=e5c890; RED=e78284
      ;;
    macchiato)
      BASE=24273a; MANTLE=1e2030; CRUST=181926; TEXT=cad3f5; SUBTEXT=a5adcb
      SURFACE0=363a4f; SURFACE1=494d64; OVERLAY0=6e738d; BLUE=8aadf4
      ROSEWATER=f4dbd6; TEAL=8bd5ca
      LAVENDER=b7bdf8; MAUVE=c6a0f6; GREEN=a6da95; YELLOW=eed49f; RED=ed8796
      ;;
    *)
      BASE=1e1e2e; MANTLE=181825; CRUST=11111b; TEXT=cdd6f4; SUBTEXT=a6adc8
      SURFACE0=313244; SURFACE1=45475a; OVERLAY0=6c7086; BLUE=89b4fa
      ROSEWATER=f5e0dc; TEAL=94e2d5
      LAVENDER=b4befe; MAUVE=cba6f7; GREEN=a6e3a1; YELLOW=f9e2af; RED=f38ba8
      ;;
  esac
}

write_sketchybar_colors() {
  local flavour="$1"
  palette "$flavour"

  cat > "$SKETCHYBAR_DIR/colors.sh" <<EOF
#!/usr/bin/env bash
# Generated by catppuccin-tiling-mode.sh
export CATPPUCCIN_FLAVOUR="$(normalise_flavour "$flavour")"
export BAR_COLOR=0xee$BASE
export ITEM_BG=0xcc$MANTLE
export ITEM_BG_ALT=0xaa$SURFACE0
export TEXT=0xff$TEXT
export SUBTEXT=0xff$SUBTEXT
export MUTED=0xff$OVERLAY0
export ACCENT=0xff$MAUVE
export ACCENT_ALT=0xff$BLUE
export SUCCESS=0xff$GREEN
export WARN=0xff$YELLOW
export ERROR=0xff$RED
export BORDER=0xff$SURFACE1
export CRUST=0xff$CRUST
export TRANSPARENT=0x00000000
EOF
}

reload_sketchybar() {
  command -v sketchybar >/dev/null 2>&1 || return 0
  pgrep -x sketchybar >/dev/null 2>&1 || return 0
  run_with_timeout 3 sketchybar --trigger catppuccin_theme_changed >/dev/null 2>&1 || true
  run_with_timeout 5 sketchybar --reload >/dev/null 2>&1 || true
}

sync_kitty_theme() {
  local flavour theme
  flavour="$(normalise_flavour "$1")"
  theme="$(kitty_theme_name "$flavour")"
  palette "$flavour"
  mkdir -p "$(dirname "$KITTY_CURRENT_THEME")"
  cat > "$KITTY_CURRENT_THEME" <<EOF
## name:     $theme
## author:   Catppuccin
## license:  MIT
## upstream: https://github.com/catppuccin/kitty

foreground              #$TEXT
background              #$BASE
selection_foreground    #$BASE
selection_background    #$ROSEWATER
cursor                  #$ROSEWATER
cursor_text_color       #$BASE
url_color               #$ROSEWATER
active_border_color     #$LAVENDER
inactive_border_color   #$OVERLAY0
bell_border_color       #$YELLOW
active_tab_foreground   #$BASE
active_tab_background   #$MAUVE
inactive_tab_foreground #$TEXT
inactive_tab_background #$SURFACE0
tab_bar_background      #$CRUST

color0 #$SURFACE1
color1 #$RED
color2 #$GREEN
color3 #$YELLOW
color4 #$BLUE
color5 #$MAUVE
color6 #$TEAL
color7 #$SUBTEXT
color8 #$SURFACE1
color9 #$RED
color10 #$GREEN
color11 #$YELLOW
color12 #$BLUE
color13 #$MAUVE
color14 #$TEAL
color15 #$TEXT
EOF

  if [[ -f "$KITTY_CONFIG" ]]; then
    local config_tmp
    config_tmp="$(mktemp "${TMPDIR:-/tmp}/kitty.conf.XXXXXX")"
    awk -v theme="$theme" '
      BEGIN { done = 0 }
      /^#[[:space:]]*Catppuccin-/ {
        if (!done) {
          print "# " theme
          done = 1
        }
        next
      }
      { print }
    ' "$KITTY_CONFIG" > "$config_tmp"
    mv "$config_tmp" "$KITTY_CONFIG"
  fi

  command -v kitty >/dev/null 2>&1 || return 0
  run_with_timeout 3 kitty @ set-colors --all --configured "$KITTY_CURRENT_THEME" >/dev/null 2>&1 ||
    run_with_timeout 3 kitty @ load-config "$KITTY_CONFIG" >/dev/null 2>&1 || true
}

current_wallpaper() {
  local wallpaper database_wallpaper
  database_wallpaper="$(/usr/bin/sqlite3 "$HOME/Library/Application Support/Dock/desktoppicture.db" \
    'SELECT d.value FROM preferences p JOIN data d ON d.rowid = p.data_id WHERE p.key = 1 AND d.value LIKE "/%" ORDER BY p.rowid DESC LIMIT 1;' \
    2>/dev/null || true)"
  if [[ -n "$database_wallpaper" && -f "$database_wallpaper" ]]; then
    printf '%s\n' "$database_wallpaper"
    return 0
  fi

  wallpaper="$(osascript -e 'tell application "System Events" to tell desktop 1 to get picture' 2>/dev/null || true)"
  if [[ -n "$wallpaper" && "$wallpaper" != "missing value" && -f "$wallpaper" ]]; then
    printf '%s\n' "$wallpaper"
  fi
}

wallpaper_for_flavour() {
  local flavour title exact
  flavour="$(normalise_flavour "$1")"
  title="$(title_flavour "$flavour")"
  exact="$WALLPAPER_DIR/Catppuccin Apple ($title).png"

  if [[ -f "$exact" ]]; then
    printf '%s\n' "$exact"
    return 0
  fi

  find "$WALLPAPER_DIR" -maxdepth 1 -type f \
    \( -iname "*$title*.png" -o -iname "*$flavour*.png" -o -iname "*$title*.jpg" -o -iname "*$flavour*.jpg" \) \
    2>/dev/null | head -n 1
}

run_with_timeout() {
  local timeout_seconds="$1"
  shift

  "$@" &
  local command_pid="$!"
  local waited=0

  while kill -0 "$command_pid" >/dev/null 2>&1; do
    if (( waited >= timeout_seconds )); then
      kill "$command_pid" >/dev/null 2>&1 || true
      wait "$command_pid" >/dev/null 2>&1 || true
      return 124
    fi
    sleep 1
    waited=$((waited + 1))
  done

  wait "$command_pid"
}

set_wallpaper() {
  local wallpaper="$1"
  [[ -f "$wallpaper" ]] || return 1
  run_with_timeout 8 osascript \
    -e 'on run argv' \
    -e 'tell application "System Events"' \
    -e 'repeat with d in desktops' \
    -e 'set picture of d to POSIX file (item 1 of argv)' \
    -e 'end repeat' \
    -e 'end tell' \
    -e 'end run' \
    "$wallpaper" >/dev/null 2>&1 || return 1
}

sync_wallpaper() {
  local flavour wallpaper
  flavour="$(normalise_flavour "$1")"
  wallpaper="$(wallpaper_for_flavour "$flavour")"
  if [[ -n "$wallpaper" ]]; then
    set_wallpaper "$wallpaper" || printf 'warning: could not set wallpaper: %s\n' "$wallpaper" >&2
  else
    printf 'warning: no %s wallpaper found in %s\n' "$flavour" "$WALLPAPER_DIR" >&2
  fi
}

sync_system_appearance() {
  local flavour
  flavour="$(normalise_flavour "$1")"
  if [[ "$flavour" == "latte" ]]; then
    run_with_timeout 5 osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to false' >/dev/null 2>&1 || true
  else
    run_with_timeout 5 osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true' >/dev/null 2>&1 || true
  fi
}

desktop_icon_state() {
  defaults read com.apple.finder CreateDesktop 2>/dev/null || printf '__unset__\n'
}

set_desktop_icons() {
  local enabled="$1"
  defaults write com.apple.finder CreateDesktop -bool "$enabled" >/dev/null
  killall Finder >/dev/null 2>&1 || true
}

active_kitty_opacity() {
  awk '
    /^[[:space:]]*background_opacity[[:space:]]+/ { print $2; found = 1; exit }
    END { if (!found) print "__unset__" }
  ' "$KITTY_CONFIG" 2>/dev/null || printf '__unset__\n'
}

remove_kitty_opacity() {
  local tmp
  [[ -f "$KITTY_CONFIG" ]] || return 0
  tmp="$(mktemp "${TMPDIR:-/tmp}/kitty.conf.XXXXXX")"
  awk '!/^[[:space:]]*background_opacity[[:space:]]+/' "$KITTY_CONFIG" > "$tmp"
  mv "$tmp" "$KITTY_CONFIG"
  command -v kitty >/dev/null 2>&1 || return 0
  kitty @ set-background-opacity --all 1 >/dev/null 2>&1 || kitty @ load-config "$KITTY_CONFIG" >/dev/null 2>&1 || true
}

save_state_once() {
  [[ -f "$STATE_DIR/active" ]] && [[ "$(cat "$STATE_DIR/active" 2>/dev/null)" == "1" ]] && return 0
  current_wallpaper > "$STATE_DIR/previous_wallpaper"
  desktop_icon_state > "$STATE_DIR/previous_desktop_icons"
  active_kitty_opacity > "$STATE_DIR/previous_kitty_opacity"
}

mark_state() {
  local active="$1"
  local flavour="$2"
  local normalised
  normalised="$(normalise_flavour "$flavour")"
  printf '%s\n' "$active" > "$STATE_DIR/active"
  printf '%s\n' "$normalised" > "$STATE_DIR/theme"
  printf '%s\n' "$normalised" > "$SKETCHYBAR_ACTIVE_THEME"
  sync_starship_palette "$normalised"
}

sync_starship_palette() {
  local flavour="$1" tmp
  [[ -f "$STARSHIP_CONFIG" ]] || return 0
  tmp="$(mktemp "${TMPDIR:-/tmp}/starship.toml.XXXXXX")"
  awk -v flavour="$flavour" '
    /^palette[[:space:]]*=/ {
      print "palette = \"catppuccin_" flavour "\""
      done = 1
      next
    }
    { print }
    END {
      if (!done) print "palette = \"catppuccin_" flavour "\""
    }
  ' "$STARSHIP_CONFIG" > "$tmp"
  mv "$tmp" "$STARSHIP_CONFIG"
}

sync_neovim_theme_state() {
  local flavour="$1"
  mkdir -p "$NVIM_STATE_DIR"
  printf 'catppuccin-%s\n' "$(normalise_flavour "$flavour")" > "$NVIM_STATE_DIR/color_theme.txt"
  printf '%s\n' "$(normalise_flavour "$flavour")" > "$NVIM_STATE_DIR/catppuccin_flavour.txt"
}

apply_mode() {
  local flavour
  flavour="$(normalise_flavour "$1")"

  save_state_once
  mark_manual_theme_choice
  write_sketchybar_colors "$flavour"
  sync_kitty_theme "$flavour"
  sync_neovim_theme_state "$flavour"
  sync_wallpaper "$flavour"
  sync_system_appearance "$flavour"

  set_desktop_icons false
  "$KITTY_OPACITY_SCRIPT" "$DEFAULT_OPACITY" >/dev/null || true
  mark_state 1 "$flavour"
  if [[ "$(cat "$STATE_DIR/jankyborders_enabled" 2>/dev/null || printf '1')" == "1" ]]; then
    "$JANKYBORDERS_SCRIPT" apply "$flavour" >/dev/null 2>&1 || true
  fi
  "$SKETCHYVIM_SCRIPT" apply >/dev/null 2>&1 || true
  reload_sketchybar
  "$SOUND_SCRIPT" play theme >/dev/null 2>&1 || true
}

restore_mode() {
  local previous_wallpaper previous_icons

  write_sketchybar_colors "$(normalise_flavour "$FLAVOUR")"
  sync_kitty_theme "$FLAVOUR"

  previous_wallpaper="$(cat "$STATE_DIR/previous_wallpaper" 2>/dev/null || true)"
  if [[ -n "$previous_wallpaper" && -f "$previous_wallpaper" ]]; then
    set_wallpaper "$previous_wallpaper" || true
  fi

  previous_icons="$(cat "$STATE_DIR/previous_desktop_icons" 2>/dev/null || printf '1\n')"
  if [[ "$previous_icons" == "__unset__" || "$previous_icons" == "1" || "$previous_icons" == "true" ]]; then
    set_desktop_icons true
  else
    set_desktop_icons false
  fi

  "$KITTY_OPACITY_SCRIPT" 100 >/dev/null || true

  mark_state 0 "$FLAVOUR"
  "$JANKYBORDERS_SCRIPT" suspend >/dev/null 2>&1 || true
  "$SKETCHYVIM_SCRIPT" suspend >/dev/null 2>&1 || true
  reload_sketchybar
  "$SOUND_SCRIPT" play toggle >/dev/null 2>&1 || true
}

case "$ACTION" in
  apply|enter|on)
    apply_mode "$FLAVOUR"
    ;;
  restore|exit|off)
    restore_mode
    ;;
  colors)
    mark_manual_theme_choice
    write_sketchybar_colors "$FLAVOUR"
    sync_kitty_theme "$FLAVOUR"
    sync_neovim_theme_state "$FLAVOUR"
    sync_wallpaper "$FLAVOUR"
    sync_system_appearance "$FLAVOUR"
    mark_state "$(cat "$STATE_DIR/active" 2>/dev/null || printf '0')" "$FLAVOUR"
    if [[ "$(cat "$STATE_DIR/jankyborders_enabled" 2>/dev/null || printf '1')" == "1" ]]; then
      "$JANKYBORDERS_SCRIPT" apply "$FLAVOUR" >/dev/null 2>&1 || true
    fi
    reload_sketchybar
    "$SOUND_SCRIPT" play theme >/dev/null 2>&1 || true
    ;;
  *)
    printf 'Usage: %s apply|restore|colors [latte|frappe|macchiato|mocha]\n' "${0##*/}" >&2
    exit 2
    ;;
esac
